name: Biome NodeJS Linter
on: 
  pull_request:
    paths-ignore: 
      - 'api/**'
jobs:
  biome:
    name: runner / Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: mongolyy/reviewdog-action-biome@v2.7.0
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          biome_flags: './src'
          fail_level: 'error'
